import "./globals.scss";
import Navbar from "./components/navbar";
import "./styles/navbar.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        {children}

        <Navbar />
      </body>
    </html>
  );
}
